name: fwdownloader
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      customDate:
        description: 'Date (yyyymmdd)'
        required: true
        default: ''

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  INPUT_CUSTOM_DATE: ${{ github.event.inputs.customDate }}

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: "3.7"
      - name: Install requirements
        run: pip install requests html2text PyGithub beautifulsoup4 lxml
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: python src/__init__.py
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "New Firmware Data"